---
title: "My Story"
---

I should title this page "Well that explains a lot!"

### Early Life

I had a decidedly unique upbringing. I was raised in the central Adirondack Park of New York State, in the state's smallest county by population (Hamilton). I graduated from Long Lake Central as the valedictorian in a grade of 7 students. My best friend was the saludatorian, and at one point it was just the two of us in middle school. We started with 7 and ended with 7, and got close but never hit double digits (9 was our max). I actually wasn't even supposed to attend Long Lake, my house was technically in the Tupper Lake school district. It was also located in the Town of Colton in St. Lawrence County, while our address was a Long Lake adresss (because of where the mailbox was, 5 miles from the house), while our phone number was a Tupper Lake number. If that's confusing to you, I don't blame you, if you found it interesting you're not alone. It was interesting enough that an AP sports writer with ties to the region, Tim Reynolds, wrote an article during my senior year which made it all the way to the NY times. The article chronicled what I found normal; hours on the bus every day, parents who would sit in the parking lot at school to pick me up from away games based on his best guess of when we would return (no cell service in the park at that point), and a community of people so tight knit that they would fill the gymnasium every spring to watch 6 or 7 seniors walk across the stage.

But back to that bit about living in a black hole. My father was the camp ranger (caretaker) for the Boy Scouts of America for 35 years. As such we lived at Sabattis Scout Reservation, a 1,500 acre Boy Scout Camp located between Long Lake and Tupper Lake, 18 miles off of route 30, with 12 miles of dirt road (to get to the bus stop), and 5 miles of private road behind a locked gate. The camp was completely off-grid, with diesel generators for power, and solar panels at the house I grew up in. My family was there year round, with volunteers, staff and campers present only from June - August. We had no internet, satellite internet (we could get 3 channels via an aerial antenna on the roof), and only a land-line phone. Unfortunately, you may have heard, the camp recently sold to Open Space Institute and will eventually transfer to state ownership. I am grateful I will be able to go back when it becomes public land, but we lost a true gem where youth were able to grow and have real valuable learning outside of a classroom. At the risk of becoming overly sentimental, I will just say that growing up there, almost an hour from my school friends, I was implicitly aware of my unique situation. I spent most of my time outdoors, fishing, biking, hiking, hunting, and trapping. My mom started taking me along at her job as Assistant Forest Ranger on Low's Lake when I was maybe 5 or 6. I would sit in the middle of the canoe and fish all day while she made her rounds, talking to people campling out, helping them to find an open campsite, reminding them of rules and regulations, fire safety, things of that nature. I would have fished sunup to sundown if she let me.

When I was maybe 11 or 12 I started hanging out down in the Boy Scout Camp, primarily at the "trip center" where I would sail around in sunfish sailboats, tend a campfire, and generally pester the director there, who would oblige me when he could with a game of "balance wars", where two people would stand at opposite ends of a windsurfer board, unable to touch each other, trying to make the other fall in the water. I spent a number of summers being a general nuisance to the staff, and disappearing into the woods with some of the other sons of staffers who weren't old enough to work yet.

At the end of each summer, my family would vacation on the coast of Maine. I loved boogie boarding in the waves, fishing for striped bass, finding seashells and seaglass, and eating lobster. My love for the ocean came from those trips, despite the 55 degree water temps. It's also where I got the worst case of hypothermia I've ever experienced after spending almost two hours snorkeling around in the rocks at low tide. Throughout high school it was much of the same. I eventually worked as staff at the scout camp, starting out teaching first year scouts, then working commissary, scoutcraft (think knots, orienteering, and wilderness survival), and eventually becoming a lifeguard, working the waterfront, I was mountain bike director the summer prior to college, and finally being my dads assistant for a summer. I know I missed out on a lot in town during those summers, but I also got to experience a lot and meet a ton of people, some of whom I am still close with today.

### College v1

Upon graduation, I enrolled at SUNY ESF in Syracuse, thanks in large part to my mother, who forced me to fill out the forms, and dragged me to friends houses in town who had internet access so we could fill out financial aid forms and the like. I actually never wanted to go to college, but also didn't have a real conviction towards any particular career path. So off to Syracuse, starting undeclared at ESF in the fall of 2008, which was a rare thing at a school with pretty specialized majors. They told me I had to decide by the end of the fall term or I probably wouldn't be able to graduate on time. Since I was undeclared I got to choose a freshman seminar to attend instead of the program specific one that majors take, and I chose the Environmental Science seminar since they had a different professor come in to talk each week. I think it was the third week when a professor came and talked about fisheries and it just clicked, this is what I want to do.

Despite my lackadaisical approach to college at first, I am grateful to have traveled that path. And despite my original plan of attending a school where I could play soccer (I was passionate about it in high school, but looking back I wasn't ever that good at it, I could just run a lot), I found myself at the woodsmen practice field one night, having hitched a ride with a couple of guys who showed up in my dorm and were heading there, who I honestly never saw again. Being on the woodsmen team became a large part of my identity at school; it was one of the greatest experiences of my time there. Generally a great group of people, and in hindsight we learned a lot by organizing and running the team, which was a club for the first two years and became wrapped under the athletic program at the start of my junior year. We traveled to Maine, Canada, and of course all over NY to compete, with the year culminating in the conclave wide "spring meet". The culmination worked out perfect; we never won a meet until our home meet our senior year. We had been working and building towards it, and then we ended up sweeping the big spring meet conclave event at Dartmouth, NH, the same place I attended my first spring meet freshman year. In addition, Stihl at that point sponsored a collegiate challenge, and I represented ESF to a second place finish at [nationals](https://www.youtube.com/watch?v=m-mSvWBxqUo). If I'd have won I would have earned an automatic bid into the rookie world championships. I often wonder if I'd have won there if I'd have continued with timbersports longer. As it were, that was the last time I picked up an axe competitively.
