---
title: "My Story"
---

I should title this page "Well that explains a lot!"

I had a decidedly unique upbringing. I was raised in the central Adirondack Park of New York State, in the state's smallest county by population (Hamilton). I graduated from Long Lake Central as the valedictorian in a grade of 7 students. My best friend was the saludatorian, and at one point it was just the two of us in middle school. We started with 7 and ended with 7, and got close but never hit double digits (9 was our max). I actually wasn't even supposed to attend Long Lake, my house was technically in the Tupper Lake school district. It was also located in the Town of Colton in St. Lawrence County, while our address was a Long Lake adresss (because of where the mailbox was, 5 miles from the house), and our phone number was a Tupper Lake number. If that's confusing to you, I don't blame you, if you found it interesting you're not alone. It was interesting enough that an AP article circulated during my senior year all the way to the NY times. Written by AP sports writer Tim Reynolds, the article chronicled what I found normal; hours on the bus every day, a father who would sit in the parking lot at school to pick me up from away games based on his best guess of when we would return (no cell service in the park at that point), and a community of people so tight knit that they would fill the gymnasium every spring to watch 6 or 7 seniors walk across the stage. 

But back to that bit about living in a black hole. See my father was the camp ranger (caretaker) for the Boy Scouts of America for 35 years. As such we lived at Sabattis Scout Reservation, a 1,500 acre Boy Scout Camp located between Long Lake and Tupper Lake, 18 miles off of route 30, with 12 miles of dirt road (to get to the bus stop), and 5 miles of private road behind a locked gate. Unfortunately, you may have heard, the camp recently sold to Open Space Institute and will eventually transfer to state ownership. I am grateful I will be able to go back, but we lost a true gem where youth were able to grow and have real valuable learning outside of a classroom. At the risk of becoming overly sentimental, I will just say that growing up there, almost an hour from my school friends, I was implicitly aware of my unique situation. I spent most of my time outdoors, fishing, biking, hiking, hunting, and trapping. My mom started taking me along at her job as Assistant Forest Ranger on Low's Lake when I was maybe 5 or 6. I would sit in the middle of the canoe and fish all day while she made her rounds, talking to people campling out, helping them to find an open campsite, reminding them of rules and regulations, fire safety, things of that nature. I would have fished sunup to sundown if she let me. 

When I was maybe 11 or 12 I started hanging out down in the Boy Scout Camp, primarily at the "trip center" where I would sail around in sunfish sailboats, tend a campfire, and generally pester the director there, who would oblige me when he could with a game of "balance wars", with either party on a windsurfer board standing, unable to touch each other, trying to make the other fall in the water. 

At the end of each summer, my family would vacation on the coast of Maine. I loved boogie boarding in the waves, fishing for striped bass, finding seashells and seaglass, and eating lobster. My love for the ocean came from those trips, despite the 55 degree water temps. Throughout high school it was much of the same. I eventually worked as staff at the scout camp, starting out teaching first year scouts, then working commissary, scoutcraft (think knots, orienteering, and wilderness survival), and eventually becoming a lifeguard, working the waterfront, and finally being my dads assistant for a summer. I missed out on a lot in town during those summers, but I also got to experience a lot and meet a ton of people, some of whom I am still close with today. 

Upon graduation, I enrolled at SUNY ESF in Syracuse. 
